- name: Checkout
  id: checkout
  uses: actions/checkout@v4

- name: Create Distr Version
  id: distr-create-version
  uses: glasskube/distr-create-version-action@v1
  with:
    api-token: ${{ secrets.DISTR_API_TOKEN }}
    application-id: 'c27c3503-e2c8-4113-8293-9bf9cceb87e3'
    version-name: 'v1.3.0'
    compose-file: ${{ github.workspace }}/docker-compose-prod.yml
    template-file: ${{ github.workspace }}/template.env

- name: Print Application Version ID
  id: output
  run: echo "${{ steps.distr-create-version.outputs.created-version-id }}"